<script lang="ts">
	import { ndk } from "$lib/ndk.svelte";
	import { goto } from "$app/navigation";
	import { NDKEvent, type NostrEvent } from "@nostr-dev-kit/ndk";
	import Button from "$lib/components/ui/button/button.svelte";
	import Input from "$lib/components/ui/input/input.svelte";
	import Label from "$lib/components/ui/label/label.svelte";
	import TiptapEditor from "$lib/components/TiptapEditor.svelte";
	import CategoryDropdown from "../a/[naddr]/CategoryDropdown.svelte";
	import { Switch } from "$lib/components/ui/switch";
	import { wysiwyg } from "$lib/stores/settings";
	import { normalizeDTag } from '$lib/utils/dtag';

	let title = $state("");
	let dTag = $state("");
	let content = $state("");
	let category = $state<string | undefined>(undefined);
	let saving = $state(false);
	let newContent = $state(true);
	let publishable = $state(true);
	let statusMessage = $state("");

	// Auto-generate d-tag from title in kebab-case
	let autoGeneratedDTag = $derived(
		title
			? normalizeDTag(title)
			: ""
	);

	// Sync auto-generated d-tag to dTag if user hasn't manually edited it
	let manuallyEdited = $state(false);
	$effect(() => {
		if (!manuallyEdited) {
			dTag = autoGeneratedDTag;
		}
	});

	// Validate and enforce kebab-case on manual d-tag edits
	function handleDTagInput(event: Event) {
		manuallyEdited = true;
		const input = event.target as HTMLInputElement;
		const value = input.value;
		const kebabCase = normalizeDTag(value);

		if (value !== kebabCase) {
			dTag = kebabCase;
		}
	}

	async function createEntry() {
		if (!title.trim() || !dTag.trim()) return;

		saving = true;
		try {
			const event = new NDKEvent(ndk, {
				kind: 30818,
				content: content,
				tags: [
					["d", dTag],
					["title", title],
					["published_at", Math.floor(Date.now() / 1000).toString()]
				]
			} as NostrEvent);

			if (category) {
				event.tags.push(["c", category]);
			}

			event.alt = `This is a wiki article about ${title}\n\nYou can read it on https://wikifreedia.xyz/a/${event.encode()}`;

			await event.publish();
			goto(`/${dTag}/${event.author.npub}`);
		} catch (error) {
			console.error("Failed to create entry:", error);
			saving = false;
		}
	}
</script>

<div class="max-w-4xl mx-auto px-6 py-8">
	<h1 class="text-3xl font-bold mb-8">Create New Entry</h1>

	<div class="space-y-6">
		<div class="space-y-2">
			<Label for="title">Title</Label>
			<Input
				id="title"
				bind:value={title}
				placeholder="e.g. Second World War"
				class="text-lg"
			/>
		</div>

		<div class="space-y-2">
			<Label for="dtag">URL Identifier (d-tag)</Label>
			<Input
				id="dtag"
				bind:value={dTag}
				oninput={handleDTagInput}
				placeholder="automatically generated from title"
				class="font-mono"
			/>
			<p class="text-sm text-muted-foreground">
				This will be used in the URL. Only lowercase letters, numbers, and hyphens allowed.
			</p>
		</div>

		<div class="space-y-2">
			<Label>Category</Label>
			<CategoryDropdown bind:value={category} />
		</div>

		<div class="space-y-2">
			<Label>Content</Label>
			<TiptapEditor
				bind:content
				bind:newContent
				bind:publishable
				bind:statusMessage
				preferRich={$wysiwyg}
				placeholder="Write in Djot format..."
			/>
		</div>

		<div class="flex items-center gap-2">
			<Switch bind:checked={$wysiwyg} />
			<Label>WYSIWYG Editor</Label>
		</div>

		<div class="flex gap-4">
			<Button
				onclick={createEntry}
				disabled={!title.trim() || !dTag.trim() || saving || !publishable}
				class="px-10"
			>
				{#if saving}
					Creating...
				{:else}
					Create Entry
				{/if}
			</Button>

			<Button
				variant="ghost"
				onclick={() => window.history.back()}
			>
				Cancel
			</Button>
		</div>

		{#if !publishable && statusMessage}
			<p class="text-sm text-amber-600">{statusMessage}</p>
		{/if}
	</div>
</div>
